### ISSUE TITLE
Does this work with Windows 11? Extreme graphical bugs

### ISSUE THREAD

**Issue by Maidenfan724** [EndlesslyFlowering/dxvk#2]
More a question than an issue but I am trying to get HDR to work with AC Odyssey on Windows 11 with DXVK and while this works to enable HDR, I get extreme graphical bugs using the provided config. HDR enables but the screen becomes covered in strange artifacts and there are all kinds of graphical bugs. If I delete the configuration file, DXVK works phenomenally to eliminate stuttering, but with the provided config it becomes unplayable. Do you know what might be causing this, and is there a solution that you know of? Any help is greatly appreciated, thank you.

**Comment by EndlesslyFlowering** [comment]
I think we solved this on discord :)
