### ISSUE TITLE
Picture is washed out and overbright

### ISSUE THREAD

**Issue by Steff833** [EndlesslyFlowering/dxvk#4]
Hi I tested two 32bit Direct9 Games.

Call of Duty - World at War 
and
Mirrors Edge.

On both games the picture color is washed out and overbright.

I tried the 32bit version of d3d9.dll from...
    dxvk_v2.4-HDR-mod-v0.3.0-gplasync-1.7z 
    dxvk_v2.4-HDR-mod-v0.3.0.7z
    dxvk_v2.3.1-HDR-mod-v0.3.0-gplasync-1.7z

config files I tried: (renamed too dxvk.conf)
• dxvk_d3d9_0_safest.conf, 
• dxvk_d3d9_1_2nd_safest.conf and 
• dxvk_d3d9_5_experimental.conf 

Only when I launch the game without a conf file the brightness looks normal. But I guess without a conf file HDR is not enabled. I tried to upload a screenshot here. But the first photo (with a dxvk.conf) is shot in an for me unknown format *.jxr. The screenshot taken without a dxvk.conf the Nvidia App shot  in normal *.png format. Another proof for me HDR is disabled without one of your dxvk.conf files.

I have Windows 10 with enabled HDR under system settings. A Nvidia Geforce GTX 1660 Super and my Monitor is an ASUS  VG32AQA1A.

MirrorsEdge_d3d9.log:
info:  Game: MirrorsEdge.exe
info:  DXVK: v2.4-HDR-mod-v0.3.0-1-gplasync
info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    d3d9.enforceWindowModeInternally = disabled
info:    d3d9.upgradeSwapChainColorSpaceTo = scRGB
info:    d3d9.upgradeSwapChainFormatTo = rgba16_sfloat
info:    d3d9.enableSwapChainUpgrade = true
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x7c5616f0
info:  Built-in extension providers:
info:    Platform WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_EXT_surface_maintenance1
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D9: back buffer upgrade disabled!
info:  D3D9: render target upgrades disabled
info:  DXVK (D3D9): swap chain format will be upgraded to:      VK_FORMAT_R16G16B16A16_SFLOAT
info:  DXVK (D3D9): swap chain color space will be upgraded to: VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 1660 SUPER:
info:    Driver : NVIDIA 555.99.0
info:    Memory Heap[0]: 
info:      Size: 5966 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[2]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8158 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x6
info:      Memory Type[4]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[5]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Game: MirrorsEdge.exe
info:  DXVK: v2.4-HDR-mod-v0.3.0-1-gplasync
info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    d3d9.enforceWindowModeInternally = disabled
info:    d3d9.upgradeSwapChainColorSpaceTo = scRGB
info:    d3d9.upgradeSwapChainFormatTo = rgba16_sfloat
info:    d3d9.enableSwapChainUpgrade = true
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x7c5616f0
info:  Built-in extension providers:
info:    Platform WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_EXT_surface_maintenance1
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D9: back buffer upgrade disabled!
info:  D3D9: render target upgrades disabled
info:  DXVK (D3D9): swap chain format will be upgraded to:      VK_FORMAT_R16G16B16A16_SFLOAT
info:  DXVK (D3D9): swap chain color space will be upgraded to: VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 1660 SUPER:
info:    Driver : NVIDIA 555.99.0
info:    Memory Heap[0]: 
info:      Size: 5966 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[2]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8158 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x6
info:      Memory Type[4]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[5]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Device properties:
info:    Device : NVIDIA GeForce GTX 1660 SUPER
info:    Driver : NVIDIA 555.99.0
info:  Enabled device extensions:
info:    VK_EXT_attachment_feedback_loop_layout
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_bias_control
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state3
info:    VK_EXT_fragment_shader_interlock
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_graphics_pipeline_library
info:    VK_EXT_hdr_metadata
info:    VK_EXT_memory_priority
info:    VK_EXT_non_seamless_cube_map
info:    VK_EXT_robustness2
info:    VK_EXT_shader_module_identifier
info:    VK_EXT_swapchain_maintenance1
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_external_memory_win32
info:    VK_KHR_external_semaphore_win32
info:    VK_KHR_maintenance5
info:    VK_KHR_pipeline_library
info:    VK_KHR_present_id
info:    VK_KHR_present_wait
info:    VK_KHR_swapchain
info:    VK_KHR_win32_keyed_mutex
info:    VK_NV_descriptor_pool_overallocation
info:    VK_NV_raw_access_chains
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    wideLines                              : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 1
info:    shaderResourceResidency                : 0
info:    shaderResourceMinLod                   : 0
info:    sparseBinding                          : 0
info:    sparseResidencyBuffer                  : 0
info:    sparseResidencyImage2D                 : 0
info:    sparseResidencyImage3D                 : 0
info:    sparseResidency2Samples                : 0
info:    sparseResidency4Samples                : 0
info:    sparseResidency8Samples                : 0
info:    sparseResidency16Samples               : 0
info:    sparseResidencyAliased                 : 0
info:  Vulkan 1.1
info:    shaderDrawParameters                   : 0
info:  Vulkan 1.2
info:    samplerMirrorClampToEdge               : 1
info:    drawIndirectCount                      : 1
info:    samplerFilterMinmax                    : 0
info:    hostQueryReset                         : 1
info:    timelineSemaphore                      : 1
info:    bufferDeviceAddress                    : 0
info:    shaderOutputViewportIndex              : 1
info:    shaderOutputLayer                      : 1
info:    vulkanMemoryModel                      : 1
info:  Vulkan 1.3
info:    robustImageAccess                      : 0
info:    pipelineCreationCacheControl           : 1
info:    shaderDemoteToHelperInvocation         : 1
info:    shaderZeroInitializeWorkgroupMemory    : 0
info:    synchronization2                       : 1
info:    dynamicRendering                       : 1
info:  VK_AMD_shader_fragment_mask
info:    extension supported                    : 0
info:  VK_EXT_attachment_feedback_loop_layout
info:    attachmentFeedbackLoopLayout           : 1
info:  VK_EXT_conservative_rasterization
info:    extension supported                    : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_depth_bias_control
info:    depthBiasControl                       : 1
info:    leastRepresentableValueForceUnormRepresentation : 1
info:    floatRepresentation                    : 0
info:    depthBiasExact                         : 1
info:  VK_EXT_extended_dynamic_state3
info:    extDynamicState3AlphaToCoverageEnable  : 1
info:    extDynamicState3DepthClipEnable        : 1
info:    extDynamicState3RasterizationSamples   : 1
info:    extDynamicState3SampleMask             : 1
info:    extDynamicState3LineRasterizationMode  : 1
info:  VK_EXT_fragment_shader_interlock
info:    fragmentShaderSampleInterlock          : 0
info:    fragmentShaderPixelInterlock           : 0
info:  VK_EXT_full_screen_exclusive
info:    extension supported                    : 1
info:  VK_EXT_graphics_pipeline_library
info:    graphicsPipelineLibrary                : 1
info:  VK_EXT_line_rasterization
info:    rectangularLines                       : 1
info:    smoothLines                            : 1
info:  VK_EXT_memory_budget
info:    extension supported                    : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_module_identifier
info:    shaderModuleIdentifier                 : 1
info:  VK_EXT_shader_stencil_export
info:    extension supported                    : 0
info:  VK_EXT_swapchain_colorspace
info:    extension supported                    : 0
info:  VK_EXT_swapchain_maintenance1
info:    swapchainMaintenance1                  : 1
info:  VK_EXT_hdr_metadata
info:    extension supported                    : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_external_memory_win32
info:    extension supported                    : 1
info:  VK_KHR_external_semaphore_win32
info:    extension supported                    : 1
info:  VK_KHR_maintenance5
info:    maintenance5                           : 1
info:  VK_KHR_present_id
info:    presentId                              : 1
info:  VK_KHR_present_wait
info:    presentWait                            : 1
info:  VK_NV_descriptor_pool_overallocation
info:    descriptorPoolOverallocation           : 1
info:  VK_NV_raw_access_chains
info:    shaderRawAccessChains                  : 1
info:  VK_NVX_binary_import
info:    extension supported                    : 0
info:  VK_NVX_image_view_handle
info:    extension supported                    : 0
info:  VK_KHR_win32_keyed_mutex
info:    extension supported                    : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:    Sparse   : 0
warn:  DXVK: No state cache file found
info:  DXVK: Graphics pipeline libraries supported
info:  D3D9: back buffer upgrade disabled!
info:  D3D9: render target upgrades disabled
info:  DXVK (D3D9): swap chain format will be upgraded to:      VK_FORMAT_R16G16B16A16_SFLOAT
info:  DXVK (D3D9): swap chain color space will be upgraded to: VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              2560
info:      - Height:             1440
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           false
info:      - Swap effect:        1
info:  DXVK (D3D9): swap chain upgrade:
info:                   from: VK_FORMAT_R8G8B8A8_UNORM + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:                   to:   VK_FORMAT_R16G16B16A16_SFLOAT + VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:  DXVK (D3D9): swap chain upgrade:
info:                   from: VK_FORMAT_R8G8B8A8_UNORM + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:                   to:   VK_FORMAT_R16G16B16A16_SFLOAT + VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R16G16B16A16_SFLOAT
info:    Color space:  VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR (dynamic: yes)
info:    Buffer size:  2560x1440
info:    Image count:  3
info:    Exclusive FS: 0
info:  Setting display mode: 2560x1440@0
info:  Setting display mode: 2560x1440@0
info:  D3D9DeviceEx::SetRenderState: MinimalNVIDIADriverShaderOptimization is unsupported
info:  DXVK: Using 8 compiler threads
info:  DXVK (D3D9): swap chain upgrade:
info:                   from: VK_FORMAT_R8G8B8A8_UNORM + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:                   to:   VK_FORMAT_R16G16B16A16_SFLOAT + VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R16G16B16A16_SFLOAT
info:    Color space:  VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR (dynamic: yes)
info:    Buffer size:  2560x1440
info:    Image count:  3
info:    Exclusive FS: 0
info:  DXVK (D3D9): swap chain upgrade:
info:                   from: VK_FORMAT_R8G8B8A8_UNORM + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:                   to:   VK_FORMAT_R16G16B16A16_SFLOAT + VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R16G16B16A16_SFLOAT
info:    Color space:  VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR (dynamic: yes)
info:    Buffer size:  160x28
info:    Image count:  3
info:    Exclusive FS: 0
info:  DXVK (D3D9): swap chain upgrade:
info:                   from: VK_FORMAT_R8G8B8A8_UNORM + VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:                   to:   VK_FORMAT_R16G16B16A16_SFLOAT + VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R16G16B16A16_SFLOAT
info:    Color space:  VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR (dynamic: yes)
info:    Buffer size:  2560x1440
info:    Image count:  3
info:    Exclusive FS: 0

I hope you can help me.

**Comment by EndlesslyFlowering** [comment]
You need additional post processing with usually ReShade with either my shaders ( https://github.com/EndlesslyFlowering/ReShade_HDR_shaders ) or the one from Pumbo ( https://github.com/Filoppi/PumboAutoHDR ).

You can also join our discord here: https://discord.gg/R2Bt3uptw6 if you have more questions :)

**Comment by EndlesslyFlowering** [comment]
any update about this?
