### ISSUE TITLE
[DXVK 2.5] AF must be forced in dxvk.conf

### ISSUE THREAD

**Issue by donizettilorenzo** [EndlesslyFlowering/dxvk#5]
It can't work just using the game setting (in every D3D9 game), why?
Is this expected? (I don't think so)

Example:
AF 16x in-game -> No AF
https://postimg.cc/ykrv5Tdn

AF forced in dxvk.conf -> OK
https://postimg.cc/qNPQBM23

(Of course I'm using your DXVK mod+SpecialK to get HDR output and it's working fine about that aspect, the only problem is the missing anisotropic filtering and SpecialK doesn't have yet the AF forcing support in Vulkan, so I must add _d3d9.samplerAnisotropy = 8_ )

**Comment by EndlesslyFlowering** [comment]
That's an issue with dxvk v2.5 it was fixed upstream with this commit:
https://github.com/doitsujin/dxvk/commit/4c09b006a5ce84b4707a0b175a800c56a28643f0
I will make a pre release version with that commit tomorrow

**Comment by donizettilorenzo** [comment]
Thanks!

**Comment by EndlesslyFlowering** [comment]
https://github.com/EndlesslyFlowering/dxvk/releases/tag/v2.5.1-HDR-mod-v0.3.0
